routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\adminController;
use App\Http\Controllers\userController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProgramController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\userController::class, 'index'])->name('user');
Route::get('/donasi/{id}', [App\Http\Controllers\userController::class, 'donasi']);
Route::get('/donasi/{id}/donasi', [App\Http\Controllers\userController::class, 'donasicreate']);
Route::post('/donasi/{id}/donasi/store', [App\Http\Controllers\userController::class, 'donasistore']);
Route::get('/daftarprogram', [App\Http\Controllers\userController::class, 'daftarprogram']);
Route::get('/program/category/{id}', [App\Http\Controllers\userController::class, 'programcategory']);
Route::get('/konfirmasi', [App\Http\Controllers\userController::class, 'konfirmasi']);
Route::post('/konfirmasi/store/{id}', [App\Http\Controllers\userController::class, 'konfirmasistore']);
Route::get('/thx/{id}', [App\Http\Controllers\userController::class, 'thx'])->name('thx');
Route::get('/konfirmasi/thx/{id}', [App\Http\Controllers\userController::class, 'thxkonfir'])->name('thxkonfir');
Route::post('/report/{id}', [App\Http\Controllers\userController::class, 'report']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/middle', [App\Http\Controllers\ProgramController::class, 'middle']);
    Route::resource('program', ProgramController::class);
    Route::get('/detailprogram/{id}', [App\Http\Controllers\ProgramController::class, 'detailprogram'])->name('detail');
    Route::get('/verify/{id}', [App\Http\Controllers\ProgramController::class, 'verify']);
    Route::get('/donasi', [App\Http\Controllers\ProgramController::class, 'donasi']);
    Route::post('/donasi/konfir/{id}', [App\Http\Controllers\ProgramController::class, 'donasikonfir']);
});

Auth::routes();

Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::group(['middleware' => ['auth']], function () {
            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::get('/dashboard', [App\Http\Controllers\adminController::class, 'index']);
            Route::get('/program', [App\Http\Controllers\adminController::class, 'program']);
            Route::resource('/kategori', KategoriController::class);
            Route::get('/published/{id}', [App\Http\Controllers\adminController::class, 'published']);
            Route::get('/selected/{id}', [App\Http\Controllers\adminController::class, 'selected']);
            Route::get('/delete/{id}', [App\Http\Controllers\adminController::class, 'destroy']);
            Route::get('/detail/{id}', [App\Http\Controllers\adminController::class, 'detail']);
            Route::get('/hapus/{id}', [App\Http\Controllers\adminController::class, 'hapusProgram']);
        });   
    });
});

resources/views/admin/detailprogram.blade.php
@extends('template.master')
@section('judul_konten')
    {{$program->title}}
@endsection
@section('main_konten')
<div class="row">
    <div class="col-md-6">
<div class="card material-card">
        <img class="card-img-top" src="{{ asset('images/program-images/'.$program->photo) }}" alt="Card image cap">
        <div class="card-body">
            <div class="d-flex no-block align-items-center mb-3">
                <span style="border-right: 1px solid #CBD2DA;" class="text-muted pr-4">Dibuat Pada : {{$program->created_at->toDateString()}}</span>
                <div class="ml-3">
                    <span style="border-right: 1px solid #CBD2DA;" class="text-muted pr-4">Berakhir Pada : {{ $program->time_is_up }}</span>
                </div>
                <div class="ml-3">
                    @if ($program->isPublished == 1)    
                        <span class="badge badge-success">Published <i class="ti-check"></i></span>
                    @else
                        <span class="badge badge-danger">Belum Dipublish</span>
                    @endif
                </div>
            </div>
            <div class="d-flex no-block align-items-center mb-3">
                <span style="color: #2cd07e; border-right: 1px solid #2cd07e;" class="pr-4">{{$program->category->category_name}}</span>
                <div class="ml-3">
                    <span style="color: #2cd07e; border-right: 1px solid #2cd07e;" class="pr-4"><i class="ti-heart"></i> {{ $program->time_is_up }} Berdonasi</span>
                </div>
                <div class="ml-3">
                    @if ($program->isSelected == 1)
                        <span class="badge badge-success">Program Pilihan <i class="ti-check"></i></span>
                    @endif
                </div>
            </div>
            <h3 class="mt-3 text-uppercase">{{$program->title}}</h3>
            <p class="mt-3 font-light">{{$program->brief_explanation}}</p>
            <div class="float-right">
                @if ($program->isPublished == 0)
                    <a class="btn btn-success waves-effect waves-light mt-2 text-white" href="/admin/published/{{$program->id}}">Publikasi</a>
                @else
                    <a class="btn btn-danger waves-effect waves-light mt-2 text-white" href="/admin/published/{{$program->id}}">Batal Publikasi</a>
                @endif
                @if ($program->isSelected == 0)
                <a class="btn btn-primary waves-effect waves-light mt-2 text-white" href="/admin/selected/{{$program->id}}">Jadikan Program Pilihan</a>
                @else
                <a class="btn btn-danger waves-effect waves-light mt-2 text-white"href="/admin/selected/{{$program->id}}">Batal Jadikan Program Pilihan</a>
                @endif
            </div>
            @if ($program->donation_collected >= $program->donation_target)
                <span class="alert alert-success float-left" >Terdanai <i class="ti-check"></i></span>
            @endif
        </div>
    </div>
    </div>
    <div class="col-md-6">
        
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
        <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#home2" role="tab"><span class="hidden-sm-up"><i class="ti-home"></i></span> <span class="hidden-xs-down">Deskripsi</span></a> </li>
        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#profile2" role="tab"><span class="hidden-sm-up"><i class="ti-user"></i></span> <span class="hidden-xs-down">Laporan Perkembangan</span></a> </li>
        <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#laporanuser" role="tab"><span class="hidden-sm-up"><i class="ti-user"></i></span> <span class="hidden-xs-down">Laporan dari User</span></a> </li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="home2" role="tabpanel">
            <div class="p-4 text-justify">
                {!! $program->description !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/kategori.blade.php
@extends('template.master')
@section('judul_konten')
    Data Kategori
@endsection
@section('main_konten')
<div class="d-sm-flex align-items-center justify-content-end mb-4">
    <a href="kategori/create" class="btn btn-primary">Tambah Kategori</a>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Data Kategori Donasi</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama Kategori</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($kategori as $dKateg)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $dKateg->category_name }}</td>
                        <td>
                            <div class="row d-flex justify-content-around align-items-center">
                                <form action="kategori/{{ $dKateg->id }}" method="POST" wire:submit.prevent="delete">  
                                    @csrf
                                    @method('DELETE')
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button type="submit" class="btn btn-danger show_confirm" data-toggle="tooltip" title='Delete'>Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/admin/laporan.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>SB Admin 2 - Dashboard</title>
    @include('layouting.head')
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @include('layouting.left-sidebar')
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                @include('layouting.navbar')
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Data Laporan</h1>
                    </div>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            @include('layouting.footer')
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    @include('layouting.script')

</body>

</html>

resources/views/admin/program.blade.php
@extends('template.master')
@section('judul_konten')
    Data Program
@endsection
@section('main_konten')
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Data Program Donasi</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Judul</th>
                            <th>Start date</th>
                            <th>Target</th>
                            <th>Terkumpul</th>
                            <th>End Date</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($program as $dProgram)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $dProgram->title }}</td>
                                <td>{{ $dProgram->created_at->format('Y-m-d') }}</td>
                                <td>{{ $dProgram->donation_target }}</td>
                                <td>{{ $dProgram->donation_collected }}</td>
                                <td>{{ $dProgram->time_is_up }}</td>
                                <td>
                                    <a href="/admin/detail/{{$dProgram->id}}" class="btn btn-warning">Detail</a>
                                </td>
                            </tr>   
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/tambahkategori.blade.php
@extends('template.master')
@section('judul_konten')
    Tambah Data Kategori
@endsection
@section('main_konten')
    <!-- Outer Row -->
    <div class="row justify-content-center">
            
        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block pl-5"><br><br>
                            <img class="img-fluid mb-5"
                            src="{{asset('template/img/undraw_posting_photo.svg')}}" alt="...">
                        </div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Kategori Program Donasi</h1><br>
                                    <p class="mb-2 text-left">Nama Kategori : </p>
                                </div>
                                <form method="POST" action="{{route('kategori.store')}}">
                                    @csrf
                                    <div class="form-group">
                                        <input id="kategori" type="text" class="form-control @error('category_name') is-invalid @enderror" name="category_name" autocomplete="category_name" autofocus>
                                        @error('category_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                    <button type="submit" class="btn btn-primary btn-user btn-block">
                                        Tambah Kategori
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
@endsection