routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\adminController;
use App\Http\Controllers\userController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProgramController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\userController::class, 'index'])->name('user');
Route::get('/donasi/{id}', [App\Http\Controllers\userController::class, 'donasi']);
Route::get('/donasi/{id}/donasi', [App\Http\Controllers\userController::class, 'donasicreate']);
Route::post('/donasi/{id}/donasi/store', [App\Http\Controllers\userController::class, 'donasistore']);
Route::get('/daftarprogram', [App\Http\Controllers\userController::class, 'daftarprogram']);
Route::get('/program/category/{id}', [App\Http\Controllers\userController::class, 'programcategory']);
Route::get('/konfirmasi', [App\Http\Controllers\userController::class, 'konfirmasi']);
Route::post('/konfirmasi/store/{id}', [App\Http\Controllers\userController::class, 'konfirmasistore']);
Route::get('/thx/{id}', [App\Http\Controllers\userController::class, 'thx'])->name('thx');
Route::get('/konfirmasi/thx/{id}', [App\Http\Controllers\userController::class, 'thxkonfir'])->name('thxkonfir');
Route::post('/report/{id}', [App\Http\Controllers\userController::class, 'report']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/middle', [App\Http\Controllers\ProgramController::class, 'middle']);
    Route::resource('program', ProgramController::class);
    Route::get('/detailprogram/{id}', [App\Http\Controllers\ProgramController::class, 'detailprogram'])->name('detail');
    Route::get('/verify/{id}', [App\Http\Controllers\ProgramController::class, 'verify']);
    Route::get('/donasi', [App\Http\Controllers\ProgramController::class, 'donasi']);
    Route::post('/donasi/konfir/{id}', [App\Http\Controllers\ProgramController::class, 'donasikonfir']);
});

Auth::routes();

Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::group(['middleware' => ['auth']], function () {
            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::get('/dashboard', [App\Http\Controllers\adminController::class, 'index']);
            Route::get('/program', [App\Http\Controllers\adminController::class, 'program']);
            Route::resource('/kategori', KategoriController::class);
            Route::get('/published/{id}', [App\Http\Controllers\adminController::class, 'published']);
            Route::get('/selected/{id}', [App\Http\Controllers\adminController::class, 'selected']);
            Route::get('/delete/{id}', [App\Http\Controllers\adminController::class, 'destroy']);
            Route::get('/detail/{id}', [App\Http\Controllers\adminController::class, 'detail']);
            Route::get('/hapus/{id}', [App\Http\Controllers\adminController::class, 'hapusProgram']);
        });   
    });
});

resources/views/template/front.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Impact Bootstrap front - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ asset('front/img/favicon.png') }}" rel="icon">
  <link href="{{ asset('front/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ asset('front/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('front/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ asset('front/vendor/aos/aos.css" rel="stylesheet') }}">
  <link href="{{ asset('front/vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
  <link href="{{ asset('front/vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- front Main CSS File -->
  <link href="{{ asset('front/css/main.css') }}" rel="stylesheet">
  <link href="{{ asset('front/css/donasi.css') }}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <section id="topbar" class="topbar d-flex align-items-center">
    
  </section><!-- End Top Bar -->

  <header id="header" class="header d-flex align-items-center">

    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="front/img/logo.png" alt=""> -->
        <h1>Donasi<span>Online</span>.</h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="/">Home</a></li>
          <li><a class="nav-link" href="/konfirmasi">Konfirmasi Pendonasian</a></li>
          @if (Auth::check())
            @if (Auth::user()->role == 1)
              <li><a href="/admin/dashboard" class="btn-admin nav-link">Kelola Admin</a></li> 
            @else
              <li><a href="/middle" class="btn-dashboard nav-link">Dashboard</a></li>
            @endif          
          @endif
          @if (!Auth::check())
          <li><a href="/login" class="active-bg">Login</a></li>
          <li><a class="nav-link" href="/register">Daftar</a></li> 
          @else
          <li><a class="btn-logout" href="{{ route('logout') }}"
            onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();" class="nav-link">Logout</a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
          @endif
          </li>
        </ul>
      </nav><!-- .navbar -->

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->
  <!-- End Header -->

  <main id="main">

    @yield('main_konten')

  </main><!-- End #main -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{{ asset('front/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ asset('front/vendor/aos/aos.js') }}"></script>
  <script src="{{ asset('front/vendor/glightbox/js/glightbox.min.js') }}"></script>
  <script src="{{ asset('front/vendor/purecounter/purecounter_vanilla.js') }}"></script>
  <script src="{{ asset('front/vendor/swiper/swiper-bundle.min.js') }}"></script>
  <script src="{{ asset('front/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
  <script src="{{ asset('front/vendor/php-email-form/validate.js') }}"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- front Main JS File -->
  <script src="{{ asset('front/js/main.js') }}"></script>

</body>

</html>

resources/views/template/mid.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="theme-color" content="#FFFFFF">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title>@yield('title')</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito|Roboto">
  <link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css">
  <link rel="stylesheet" href="{{asset('middle-assets/css/themes/comfort.min.css')}}" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.2.1/css/bootstrap-grid.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
</head>

<body>
  <div class="sidebar">
    <div class="sidebar-header">
      <span class="brand"><small>{{Auth::user()->name}}</small></span>
      <div class="sidebar-control"><i class="la la-navicon"></i></div>
    </div>
    <div class="sidebar-wrapper">
      <ul class="list-menu">
        <li class="header">NAVIGASI</li>
        <li class="has-children">
        <a href="/middle"><i class="la la-dashboard"></i><span>Dashboards</span></a>
        </li>

        <li class="has-children">
        <a href="/donasi"><i class="la la-dashboard"></i><span>Donasi</span></a>
        </li>
         
        <li class="has-children"><a href="{{route('program.create')}}"><i class="la la-dashboard"></i><span>Buat Program Baru</span></a></li>

        <li class="has-children"><a href="{{route('program.index')}}"><i class="la la-pencil"></i><span>Daftar Program</span></a></li>

      </ul>
    </div>
  </div>
  <div class="main-content">
    <div class="header">
      <div class="left">
        <span><strong>@yield('title')</strong></span>
      </div>
      <ul class="right">
        <li class="header-user dropdown ml-4 mr-3"><a class="user-photo trigger-dropdown"><img class="user-img" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/101e1fb9-0b2e-4f2d-acfb-a777dc48f629/d4sn4w7-2a5d1fdf-2af2-408a-9300-08f28cd12951.png" /></a>
          <div class="dropdown-box with-header">
            <div class="dropdown-header"><img class="user-img user-img--lg" src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/intermediary/f/101e1fb9-0b2e-4f2d-acfb-a777dc48f629/d4sn4w7-2a5d1fdf-2af2-408a-9300-08f28cd12951.png" />
              <div class="user-info">
                <h3>{{Auth::user()->name}}</h3><span class="helper-text">{{Auth::user()->email}}</span>
              </div>
            </div>
            <ul class="dropdown-body">
              <li><a href="#"><i class="la la-user"></i><span>My profile</span></a></li>
              <li><a href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 <i class="la la-power-off"></i><span>Log out</span></a>
                 <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
              </form>
                </li>
            </ul>
          </div>
        </li>
      </ul>
      <div class="right--mobile"><a class="header-item--mobile sidebar-control"><i class="la la-navicon"></i></a></div>
    </div>
    <div class="content-wrapper">
      <div class="container-fluid">
        
        @yield('content')

      </div>
    </div>
  </div>
  <script src="{{asset('middle-assets/js/main.min.js')}}"></script>
  <script src="{{asset('middle-assets/js/chartDemoWidget.min.js')}}"></script>
  @yield('script')
  @include('sweetalert::alert')

</body>

</html>