routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\adminController;
use App\Http\Controllers\userController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProgramController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\userController::class, 'index'])->name('user');
Route::get('/donasi/{id}', [App\Http\Controllers\userController::class, 'donasi']);
Route::get('/donasi/{id}/donasi', [App\Http\Controllers\userController::class, 'donasicreate']);
Route::post('/donasi/{id}/donasi/store', [App\Http\Controllers\userController::class, 'donasistore']);
Route::get('/daftarprogram', [App\Http\Controllers\userController::class, 'daftarprogram']);
Route::get('/program/category/{id}', [App\Http\Controllers\userController::class, 'programcategory']);
Route::get('/konfirmasi', [App\Http\Controllers\userController::class, 'konfirmasi']);
Route::post('/konfirmasi/store/{id}', [App\Http\Controllers\userController::class, 'konfirmasistore']);
Route::get('/thx/{id}', [App\Http\Controllers\userController::class, 'thx'])->name('thx');
Route::get('/konfirmasi/thx/{id}', [App\Http\Controllers\userController::class, 'thxkonfir'])->name('thxkonfir');
Route::post('/report/{id}', [App\Http\Controllers\userController::class, 'report']);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/middle', [App\Http\Controllers\ProgramController::class, 'middle']);
    Route::resource('program', ProgramController::class);
    Route::get('/detailprogram/{id}', [App\Http\Controllers\ProgramController::class, 'detailprogram'])->name('detail');
    Route::get('/verify/{id}', [App\Http\Controllers\ProgramController::class, 'verify']);
    Route::get('/donasi', [App\Http\Controllers\ProgramController::class, 'donasi']);
    Route::post('/donasi/konfir/{id}', [App\Http\Controllers\ProgramController::class, 'donasikonfir']);
});

Auth::routes();

Route::group(['middleware' => 'App\Http\Middleware\AdminMiddleware'], function () {
    Route::group(['prefix' => 'admin'], function () {
        Route::group(['middleware' => ['auth']], function () {
            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::get('/dashboard', [App\Http\Controllers\adminController::class, 'index']);
            Route::get('/program', [App\Http\Controllers\adminController::class, 'program']);
            Route::resource('/kategori', KategoriController::class);
            Route::get('/published/{id}', [App\Http\Controllers\adminController::class, 'published']);
            Route::get('/selected/{id}', [App\Http\Controllers\adminController::class, 'selected']);
            Route::get('/delete/{id}', [App\Http\Controllers\adminController::class, 'destroy']);
            Route::get('/detail/{id}', [App\Http\Controllers\adminController::class, 'detail']);
            Route::get('/hapus/{id}', [App\Http\Controllers\adminController::class, 'hapusProgram']);
        });   
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'no_hp',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/userController.php
<?php

namespace App\Http\Controllers;

use App\Models\Program;
use App\Models\Development;
use App\Models\Donation;
use App\Models\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class userController extends Controller
{
    public function index()
    {
        $program = Program::orderBy('created_at', 'asc')->where('isPublished', 1)->get();

        foreach ($program as $prog) {
            $last_date = $prog->created_at;
            $current_date = $prog->time_is_up;

            //NUMBER DAYS BETWEEN TWO DATES CALCULATOR
            $start_date = \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $last_date);
            $end_date = \Carbon\Carbon::createFromFormat('Y-m-d', $current_date);
            $different_days = $start_date->diffInDays($end_date);
        }

        return view('welcome', compact('program', 'different_days'));
    }

    public function donasi($id){
        $program = Program::find($id);
        $donatur = $program->donatur->where('isVerified',1);
        $devs = Development::where('program_id', $program->id)->get();
        return view('donasi', compact('program', 'devs','donatur'));
    }

    public function donasicreate($id){
        $program = Program::find($id);
        return view('createdonasi', ['program' => $program]);
    }

    public function donasistore(Request $request){
        $donatur = new Donation;
        $id_donatur_terakhir = $donatur->max('id');
        $kode_awal = '12';
        $id_program = $request->program_id;
        $id_transaksi = $kode_awal . sprintf(abs($id_program + 2)) . sprintf("%03s", abs($id_donatur_terakhir + 1));
        $donatur->program_id = $request->program_id;
        $donatur->users_id = $request->users_id;
        $donatur->id_transaksi = $id_transaksi;
        $donatur->nama_donatur = $request->nama_donatur;
        $donatur->nominal_donasi = $request->nominal_donasi;
        $donatur->email = $request->email;
        $donatur->dukungan = $request->dukungan;
        $donatur->save();

        return redirect()->route('thx', ['id' => $donatur->id]);
    }

    public function daftarprogram(Request $request){
        if($request->has('search')){
            $programs = Program::where('title', 'LIKE', '%'.$request->search.'%')->get();
        }else{
            $programs = Program::all()->where('isPublished',1);
        }
        $categories = Kategori::all();
        return view('daftarprogram', ['categories' => $categories], ['programs' => $programs]);
    }

    public function programcategory($id){
        $programCategory = Kategori::find($id);
        $categories = Kategori::all();
        $programs = Program::all();
        return view('programcategory', compact('programCategory', 'categories', 'programs'));
    }

    public function konfirmasi(Request $request){
        $donaturs = Donation::where('id_transaksi', $request->search)->where('isVerified', 0)->get();

        return view('konfirmasi', compact('donaturs'));
    }     
    
    public function konfirmasistore(Request $request, $id){
        $konfirmasi = Donation::where('id_transaksi', $id)->first();
        $collected = Donation::where('program_id', $konfirmasi->program_id)->sum('nominal_donasi');
        $program = Program::where('id', $konfirmasi->program_id)->first();
        if($request->file('bukti_pembayaran')){
            $file       = $request->file('bukti_pembayaran');
            $fileName   = $file->getClientOriginalName();
            $request->file('bukti_pembayaran')->move("images/bukti_pembayaran/", $fileName);
            $bukti = $konfirmasi->bukti_pembayaran = $fileName;
            $konfirmasi->update(['isVerified' => 1, 'bukti_pembayaran' => $bukti]);
        }
         
        $program->update(['donation_collected' => $collected]);
            
        return redirect()->route('thxkonfir', ['id' => $konfirmasi->id]);
    }

    public function thx($id){
        $donatur = Donation::find($id);
        $program = Program::where('id', $donatur->program_id)->first();
        return view('thx', compact('donatur', 'program'));
    }

    // public function report(Request $request){
    //     Report::create($request->all());
    //     Alert::success('Laporan Dikirim', 'Terima Kasih telah mengirimkan laporan');
    //     return redirect()->back();
    // }

    public function thxkonfir($id){
        $donatur = Donation::find($id);
        $program = Program::where('id', $donatur->program_id)->first();
        return view('thxkonfir', compact('donatur', 'program'));
    }

}

resources/views/user/createProgram.blade.php
@extends('template.mid')

@section('title')
    Tambah Program
@endsection
<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="{{asset('middle-assets/css/file.css')}}">
<style>
textarea{
  height: 250px;
}

input, select, textarea{
  border: 1px solid #CDD3DB !important;
}

[type="date"] {
  background: url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png)  99% 50% no-repeat ;
}
[type="date"]::-webkit-inner-spin-button {
  display: none;
}
[type="date"]::-webkit-calendar-picker-indicator {
  opacity: 0;
}

[type="date"] {
  border: 1px solid #CDD3DB;
  border-radius: 3px;
  background-color: #fff;
  height: 42px;
  padding: 3px 5px;
}

.small{
      color: #09264A;
}
</style>

@section('content')
    
    <div class="box">
        <div class="box-header">
          <h3>Tambah Data</h3>
        </div>
        <div class="box-body">
      <form action="{{route('program.store')}}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}

        <input type="hidden" name="users_id" value="{{Auth::user()->id}}">

        <div class="form-group"><label>Kategori</label><select name="category_id">
            <option disabled selected>-- Pilih Kategori --</option>
            @foreach ($categories as $category)
            <option value="{{$category->id}}">{{$category->category_name}}</option>
            @endforeach
          </select></div>

        <div class="form-group label--floating"><input type="text" name="title"><label>Judul Program</label></div>

        <div class="file-upload-wrapper" data-text="Tambahkan Gambar">
          <input type="file" name="photo" class="file-upload-field">
        </div>
  
        <div class="form-group label--floating mt-2">
          <input type="text" name="brief_explanation" placeholder=""><label>Kalimat Ajakan</label></div>

        <div class="form-group label--floating"><input type="text" class="{{ $errors->has('donation_target') ? ' is-invalid' : '' }}" name="donation_target" value="{{ old('donation_target') }}"><label>Target Donasi</label></div>

        @if ($errors->has('donation_target'))
             <span class="invalid-feedback" role="alert">
                <div class="alert alert--dismissible">
                    <p><span>Target Donasi Harus Berupa Angka</span></p>
                    <div class="alert-dismiss"><button class="btn btn-icon"><i class="la la-times"></i></button></div>
                </div>
             </span>
        @endif

        <div class="form-group">
            <label for="time_is_up">Donasi Berakhir</label>
            <input type="date" name="time_is_up" id="time_is_up">
        </div>

        <div class="form-group label--floating">
            <input type="text" name="shelter_account_number"><label>Nomor Rekening Penampungan</label>
        </div>

        <label><small class="small">Deskripsi Program</small></label><br>
        <div class="alert alert--info alert--dismissible">
            <p><span>Isi Deskripsi Program dengan Selengkap-lengkapnya, Boleh Memasukan Gambar atau Foto</span></p>
            <div class="alert-dismiss"><button class="btn btn-icon"><i class="la la-times"></i></button></div>
        </div>
      
        <textarea name="description" class="form-control my-editor"></textarea>
      
        <div class="mt-4 box-footer"><button class="btn btn-md btn-primary">Submit</button></div>
    
      </form>
      </div>

@endsection
@section('script')  
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 

@endsection

resources/views/user/detailprogram.blade.php
@extends('template.mid')

@section('title')
    Daftar Program
@endsection  

<style>
* {
  margin: 0;
  padding: 0;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
td,th{
  width: 100px;
}
img{
    width: 100%;
    height: auto;
}
.img-bukti:hover{
  transform: scale(1.1);
  /* position: absolute; */
  
}
.tab-body{
  text-align: justify !important;
}
.desc-program{
  overflow-wrap: break-word;
  word-wrap: break-word;
}
.tab__nav-item{
    padding-left: 55px !important;
}
ul { list-style-type: none; }
.accordion {
  width: 100%;
  margin: 30px auto 20px;
  background: #B8D8E0;
  -webkit-border-radius: 4px;
  -moz-border-radius: 4px;
  border-radius: 4px;
}
.accordion .link {
  cursor: pointer;
  display: block;
  padding: 15px 15px 15px 42px;
  color: #4D4D4D;
  font-size: 14px;
  font-weight: 700;
  border-bottom: 1px solid #CCC;
  position: relative;
  -webkit-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  transition: all 0.4s ease;
}
.accordion li:last-child .link { border-bottom: 0; }
.accordion li i {
  position: absolute;
  top: 16px;
  left: 12px;
  font-size: 18px;
  color: #595959;
  -webkit-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  transition: all 0.4s ease;
}
.accordion li i.fa-chevron-down {
  right: 12px;
  left: auto;
  font-size: 16px;
}
.accordion li.open .link { color: #b63b4d; }
.accordion li.open i { color: #b63b4d; }
.accordion li.open i.fa-chevron-down {
  -webkit-transform: rotate(180deg);
  -ms-transform: rotate(180deg);
  -o-transform: rotate(180deg);
  transform: rotate(180deg);
}
/**
 * Submenu
 -----------------------------*/
.submenu {
  display: none;
  background: #FCF5EF;
  font-size: 14px;
}
</style>

@section('content')    
    <section class="section-1">
            <div class="row">
                <div class="col-lg-6">
            <div class="card responsive">
                <img src="{{$program->getFoto()}}">
                <div class="container mt-2">
                    <p>{{$program->title}}</p><br>
                    <span>Kategori : </span><span class="badge badge-succes">{{$program->category->category_name}}</span><hr>
                    <span>{{$program->brief_explanation}}</span>

                    <table class="table table--bordered table--responsive">
                        <tbody>
                            <tr>
                                <td>Donasi Dibuat</td>
                                <td>{{$program->created_at->toDateString()}}</td>
                            </tr>
                            <tr>
                                <td>Berakhir Pada</td>
                                <td>{{$program->time_is_up}}</td>
                            </tr>
                            <tr>
                                <td>Target Donasi</td>
                                <td>{{$program->donation_target}}</td>
                            </tr>
                            <tr>
                                <td>Donasi Terkumpul</td>
                                <td>{{$program->donation_collected}}</td>
                            </tr>
                            <tr>
                                <td>Nomor Rekening Penampungan</td>
                                <td>{{$program->shelter_account_number}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="tab">
                <div class="tab-header">
                  <ul class="tab__navigation">
                    <li class="tab__nav-item active" data-tab="#tab1-1">Deskripsi Program</li>
                    <li class="tab__nav-item" data-tab="#tab1-2">Laporan Perkembangan</li>
                  </ul>
                </div>

                <div class="tab-body">
                  <div class="tab__content" id="tab1-1">
                    <p class="desc-program">{!! $program->description !!}</p>
                  </div>

                  <div class="tab__content" id="tab1-2" style="display: none;">
                    @if ($program->isPublished == 1)
                    <a href="/laporanperkembangan/create/{{$program->id}}">Buat Laporan Baru</a>                    
                    @else
                    <span class="alert alert--warning">Tidak bisa buat laporan perkembangan, Program belum di publish Admin</span>
                    @endif


                    {{-- <ul id="accordion" class="accordion">
                        @php
                            $i = 1;
                        @endphp
                        @foreach ($devs as $dev)
                        <li>
                          <div class="link"><i class="fa fa-database"></i>UPDATE #{{$i}}<i class="fa fa-chevron-down"></i></div>
                          <ul class="submenu">
                              <div class="container">
                              <h2><strong>{{$dev->title}}</strong></h2>
                            <p class="pt-2">{!! $dev->description !!}</p>
                              </div>
                        </ul>
                        </li>
                        @php
                            $i++;
                        @endphp
                        @endforeach
                    </ul> --}}

                  </div>
                </div>
            </div>
            </div>

            <div class="col-lg-6">

                <div class="box box--dark">
                    <div class="box-header">
                      <h3>Pendonasi</h3>
                    </div>
                    <div class="box-body pt-0 px-0 responsive">
                      
                      <table class="table--dark">
                        @if ($donatur == 0)
                            <tr>
                              <th>Belum ada yang mendonasi</th>
                            </tr>
                        @else
                            
                        <thead>
                          <tr>
                            <th>Nama Donatur</th>
                            <th>Nominal Donasi</th>
                            <th>Bukti Pembayaran</th>
                          </tr>
                        </thead>
                        <tbody>
                          @foreach ($program->donatur as $donatur)
                          <tr>
                            <td>{{$donatur->nama_donatur}}</td>
                            <td>{{$donatur->nominal_donasi}}</td>

                            @if ($donatur->bukti_pembayaran == '')
                                <td><p class="badge badge-green">Belum Konfirmasi</p></td>
                            @else    
                                <td> <img class="img-bukti" src="{{$donatur->getFoto()}}"> </td>
                            @endif
                          
                          </tr>
                          @endforeach
                        </tbody>
                        @endif

                      </table>

                    </div>
                    <div class="pagination-wrapper clearfix">
                      <ul class="pagination float--right">
                        <li class="pagination-item"><a class="active">1</a></li>
                        <li class="pagination-item"> <a>2</a></li>
                        <li class="pagination-item"> <a>3</a></li>
                        <li class="pagination-item"> <a>Next</a></li>
                      </ul>
                    </div>
                  </div>

            </div>



            </div>
    </section>

    @section('script')
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script>
            $(function() {
	var Accordion = function(el, multiple) {
		this.el = el || {};
		this.multiple = multiple || false;
		// Variables privadas
		var links = this.el.find('.link');
		// Evento
		links.on('click', {el: this.el, multiple: this.multiple}, this.dropdown)
	}
	Accordion.prototype.dropdown = function(e) {
		var $el = e.data.el;
			$this = $(this),
			$next = $this.next();
		$next.slideToggle();
		$this.parent().toggleClass('open');
		if (!e.data.multiple) {
			$el.find('.submenu').not($next).slideUp().parent().removeClass('open');
		};
	}	
	var accordion = new Accordion($('#accordion'), false);
});
        </script>
    @endsection

@endsection

resources/views/user/edit.blade.php
@extends('template.mid')

@section('title')
    Edit Program
@endsection

<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="{{asset('middle-assets/css/file.css')}}">
<style>
textarea{
  height: 250px;
}
[type="date"] {
  background: url(https://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/calendar_2.png)  99% 50% no-repeat ;
}
[type="date"]::-webkit-inner-spin-button {
  display: none;
}
[type="date"]::-webkit-calendar-picker-indicator {
  opacity: 0;
}
[type="date"] {
  border: 1px solid #CDD3DB;
  border-radius: 3px;
  background-color: #fff;
  height: 42px;
  padding: 3px 5px;
}
.small{
      color: #09264A;
}
.image{
    width: 400px;
    height: 220px;
}
.image img{
    width: 100%;
    height: 100%;
}
.image label{
    font-size: 12.9px;
    color: #09264A;
}
</style>

@section('content')
    
    <div class="box">
        <div class="box-header">
          <h3>Tambah Data</h3>
        </div>
        <div class="box-body">
      <form action="{{route('program.update', $program->id)}}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('PUT') }}

        <input type="hidden" name="users_id" value="{{Auth::user()->id}}">
        <div class="form-group"><label>Kategori</label>
          <select name="category_id">
          <option disabled selected>-- Pilih Kategori --</option>
          @foreach ($categories as $category)
          <option value="{{$category->id}}" @if ($program->category_id == $category->id)
              {{"selected"}}
          @endif>{{$category->category_name}}</option>
          @endforeach
        </select></div>

        <div class="form-group label--floating"><input type="text" name="title" value="{{$program->title}}"><label>Judul Program</label></div>

        <div class="file-upload-wrapper" data-text="Tambahkan Gambar">
          <input type="file" name="photo" value="{{$program->photo}}" class="file-upload-field">
        </div>
        <br>
        <div class="image">
            <label>Foto yang dipakai</label>
            <img src="{{$program->getFoto()}}"s>
        </div>
        <br><br>

        <div class="form-group label--floating mt-2"><input type="text" name="brief_explanation" value="{{$program->brief_explanation}}"><label>Penjelasan Singkat</label></div>

        <div class="form-group label--floating"><input type="text" value="{{$program->donation_target}}" class="{{ $errors->has('donation_target') ? ' is-invalid' : '' }}" name="donation_target" value="{{ old('donation_target') }}"><label>Target Donasi</label></div>

        @if ($errors->has('donation_target'))
             <span class="invalid-feedback" role="alert">
                <div class="alert alert--dismissible">
                    <p><span>Target Donasi Harus Berupa Nomor</span></p>
                    <div class="alert-dismiss"><button class="btn btn-icon"><i class="la la-times"></i></button></div>
                </div>
             </span>
        @endif

        <div class="form-group">
            <label for="time_is_up">Donasi Berakhir</label>
            <input type="date" name="time_is_up" id="time_is_up" value="{{$program->time_is_up}}">
        </div>

        <div class="form-group label--floating">
            <input type="text" name="shelter_account_number" value="{{$program->shelter_account_number}}"><label>Nomor Rekening Penampungan</label>
        </div>

        <label><small class="small">Deskripsi Program</small></label><br>
        <div class="alert alert--info alert--dismissible">
            <p><span>Isi Deskripsi Program dengan Selengkap-lengkapnya</span></p>
            <div class="alert-dismiss"><button class="btn btn-icon"><i class="la la-times"></i></button></div>
        </div>
        <textarea name="description" class="form-control">{{$program->description}}</textarea>
        <div class="mt-4 box-footer"><button class="btn btn-md btn-primary">Submit</button></div>
    
      </form>
      </div>

@endsection
@section('script')  
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
<script>
  $("form").on("change", ".file-upload-field", function(){ 
    $(this).parent(".file-upload-wrapper").attr("data-text",$(this).val().replace(/.*(\/|\\)/, '') );
});
</script>
@endsection

resources/views/user/index.blade.php
@extends('template.mid')

@section('title')
    Dashboard
@endsection                 

@section('content')
    
<div class="row">
        <div class="col-md-4">
          <div class="card card-simple-1">
            <div class="card-body"><i class="la la-user"></i>
              <div class="card-content">
                <h4>Program Dibuat</h4>
                <p>{{$program}}</p>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card card-simple-1">
            <div class="card-body"><i class="la la-newspaper-o"></i>
              <div class="card-content">
                <h4>Program Dipublish</h4>
                <p>{{$programPublished}}</p>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card card-simple-1">
            <div class="card-body"><i class="la la-newspaper-o"></i>
              <div class="card-content">
                <h4>Berdonasi</h4>
                <p>-</p>
              </div>
            </div>
          </div>
        </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card card-simple-1">
          <div class="card-body"><i class="la la-calendar"></i>
            <div class="card-content">
              <h4>Program Belum Dipublsih (Dalam Proses)</h4>
              <p>{{$programNotPublished}}</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-simple-1">
          <div class="card-body"><i class="la la-shopping-cart"></i>
            <div class="card-content">
              <h4>Belum Konfirmasi</h4>
              <p>-</p>
            </div>
          </div>
        </div>
      </div>
</div>

@endsection

resources/views/user/program.blade.php
@extends('template.mid')

@section('title')
    Daftar Program
@endsection

<style>
 
  img{
    width: 100%;
  }
  .create{
    font-size: 25px;
    font-weight: bold;
  }
 p{
   font-weight: normal !important;
   font-size: 14px !important;
 }
 .btn{
   width: 100%;
 }
</style>

@section('content')
@if ($info == 0)
    <h2 class="alert alert-info">Anda Belum memiliki Program Apapun</h2>
    <a href="/program/create">Buat Program Baru</a>
@endif
<section class="section-1">
  <div class="row">
    @foreach ($programs as $program)
    <div class="col-lg-4">
      <div class="card">
            <img src="{{$program->getFoto()}}">

            <div class="container mt-3">
            @if ($program->isPublished == 1)
            <span class="badge badge-green">Published</span> 
            @else
            <span class="badge badge-red">Dalam Proses</span>             
            @endif
            @if ($program->donation_collected >= $program->donation_target)
                <span class="badge badge-green">Terdanai <i class="la la-check"></i></span>
            @endif
            <h4 class="mt-2">{{$program->title}}</h4><br>
            <p>{{$program->brief_explanation}}</p> <hr>

            <p>Kategori : <span class="badge badge-warning">
              {{$program->category->category_name}}
            </span></p><br>
            <p>Mulai Pada : <span>{{$program->created_at->toDateString()}}</span></p>
            
            
            </div>
          <div class="container mt-4">
            <div class="row">
              <div class="col-6">
                <a class="btn btn-c-warning" style="color: white" href="/detailprogram/{{$program->id}}">Detail Program</a>
              </div>
              <div class="col-6">
                <a class="btn btn-c-warning" style="color: white" href="{{route('program.edit', $program->id)}}" >Edit Program</a>
              </div>
            </div>
            <div class="row mt-4">
              <div class="col">
                <form action="{{route('program.destroy', $program->id)}}" method="post">
                  {{ csrf_field() }}
                  {{ method_field('DELETE') }}
                  <button type="submit" class="btn btn-c-danger">Hapus</button>
                </form>
              </div>
            </div>
          </div>
          </div>
      </div>
        @endforeach
      </div>
</section>


@endsection